import { Menu } from "../../modules/menuitems/models/Menu";
import { WelcomeMessage } from "../../modules/menuitems/models/WelcomeMessage";
import { Types } from "mongoose";

export class MenuSeeder {
  async shouldSeed(): Promise<boolean> {
    try {
      const menuCount = await Menu.countDocuments();
      const welcomeMessageCount = await WelcomeMessage.countDocuments();

      return menuCount === 0 && welcomeMessageCount === 0;
    } catch (error) {
      console.error("❌ Erro ao verificar dados existentes:", error);
      return false;
    }
  }

  async seed(): Promise<void> {
    try {
      // Verificar se já existem dados
      const shouldSeed = await this.shouldSeed();
      if (!shouldSeed) {
        console.log("✅ Banco de dados já possui dados. Seed não necessário.");
        return;
      }

      console.log("🌱 Iniciando seed do banco de dados...");

      // Dados COMPLETOS dos menus
      const menusData = [
        // MENUS PRINCIPAIS (1-15)
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8e4"),
          title: "📝 Ser Membro",
          description: "Faça parte da nossa família",
          type: "submenu",
          parentId: null,
          order: 1,
          isActive: true,
          requiredRole: "user",
          icon: "member",
          quickReply: true,
          content: "",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "members", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.639Z"),
          updatedAt: new Date("2025-11-21T02:39:30.639Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8e5"),
          title: "🙏 Oração",
          description: "Envie seu pedido de oração",
          type: "submenu",
          parentId: null,
          order: 2,
          isActive: true,
          requiredRole: "user",
          icon: "prayer",
          quickReply: true,
          content: "",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "prayer", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.639Z"),
          updatedAt: new Date("2025-11-21T02:39:30.639Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8e6"),
          title: "👨‍💼 Pastor",
          description: "Fale com nosso pastor",
          type: "info",
          parentId: null,
          order: 3,
          isActive: true,
          requiredRole: "user",
          icon: "pastor",
          quickReply: false,
          content:
            "*Contatos do Pastor:*\n📞 Telefone: +258 84 123 4567\n✉️ E-mail: pastor@cfcpush.org\n\n*Horários de Atendimento:*\nSegunda a Sexta: 14h-18h\nSábado: 9h-12h\n\n*Local:* Gabinete Pastoral - Sede CFC PUSH",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "pastor", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.639Z"),
          updatedAt: new Date("2025-11-21T02:39:30.639Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8e7"),
          title: "⏰ Cultos",
          description: "Horários de cultos e eventos",
          type: "info",
          parentId: null,
          order: 4,
          isActive: true,
          requiredRole: "user",
          icon: "schedule",
          quickReply: false,
          content:
            "*Horários de Cultos:*\n\n📅 *DOMINGO*\n8h30 - Culto de Celebração Principal\n\n📅 *QUARTA-FEIRA*\n18h00 - Oração e Estudo Bíblico\n\n📅 *SEXTA-FEIRA*\n18h00 - CFC PUSH Jovens\n\n📅 *SÁBADO*\n16h00 - Escola Bíblica e Discipulado\n\n*Transmissão Online:*\nDisponível em nosso site",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "schedule", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.639Z"),
          updatedAt: new Date("2025-11-21T02:39:30.639Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8e8"),
          title: "💝 Contribuir",
          description: "Faça sua contribuição",
          type: "info",
          parentId: null,
          order: 5,
          isActive: true,
          requiredRole: "user",
          icon: "donation",
          quickReply: false,
          content:
            "*Métodos de Contribuição:*\n\n🏦 *Transferência Bancária:*\nBanco: BCI\nConta: 123456789012\nNIB: 0008000123456789012\n\n📱 *Mobile Money (M-Pesa):*\nNúmero: +258 84 500 6000\nNome: CFC PUSH Igreja\n\n💵 *Coleta nos Cultos:*\nDurante os cultos presenciais",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "donations", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.640Z"),
          updatedAt: new Date("2025-11-21T02:39:30.640Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8e9"),
          title: "🏠 Visita",
          description: "Solicite visita pastoral",
          type: "link",
          parentId: null,
          order: 6,
          isActive: true,
          requiredRole: "user",
          icon: "visit",
          quickReply: false,
          content:
            "🎯 *SOLICITAR VISITA PASTORAL*\n\nPreencha o formulário para agendar uma visita pastoral em sua casa.\n\n*O que oferecemos:*\n🙏 Aconselhamento espiritual\n📖 Estudo bíblico personalizado\n💝 Apoio e acompanhamento\n🏠 Oração pelo seu lar\n\n*Tempo de resposta:* 24-48 horas\n\n🔗 *Clique no link abaixo:*\nhttps://cfcpush.org/form/pastoral-visit\n\n*Volte aqui após preencher o formulário!*",
          url: "https://cfcpush.org/form/pastoral-visit",
          payload: "",
          keywords: [],
          metadata: { module: "visits", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.640Z"),
          updatedAt: new Date("2025-11-21T02:39:30.640Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8ea"),
          title: "🤝 Assistência",
          description: "Solicite ajuda social",
          type: "submenu",
          parentId: null,
          order: 7,
          isActive: true,
          requiredRole: "user",
          icon: "assistance",
          quickReply: true,
          content: "",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "assistance", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.640Z"),
          updatedAt: new Date("2025-11-21T02:39:30.640Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8eb"),
          title: "🔔 Núcleos",
          description: "Participe de um núcleo",
          type: "submenu",
          parentId: null,
          order: 8,
          isActive: true,
          requiredRole: "user",
          icon: "nucleus",
          quickReply: false,
          content: "",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "nucleus", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.640Z"),
          updatedAt: new Date("2025-11-21T02:39:30.640Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8ec"),
          title: "🎵 Ministérios",
          description: "Conheça nossos ministérios",
          type: "submenu",
          parentId: null,
          order: 9,
          isActive: true,
          requiredRole: "user",
          icon: "ministry",
          quickReply: false,
          content: "",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "ministries", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.640Z"),
          updatedAt: new Date("2025-11-21T02:39:30.640Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8ed"),
          title: "🎯 Evangelização",
          description: "Participe da evangelização",
          type: "info",
          parentId: null,
          order: 10,
          isActive: true,
          requiredRole: "user",
          icon: "evangelism",
          quickReply: false,
          content:
            "*Próximos Eventos de Evangelização:*\n\n🔹 *Evangelismo de Rua*\nSábado, 15h00 - Centro da Cidade\n\n🔹 *Visitação Hospitalar*\nQuintas, 10h00 - Hospital Central\n\n🔹 *Campanha Jovens*\nSextas, 18h00 - Sede CFC PUSH\n\n*Como Participar:*\nCompareça aos treinamentos ou entre em contato",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "evangelism", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.640Z"),
          updatedAt: new Date("2025-11-21T02:39:30.640Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8ee"),
          title: "🤝 Servos",
          description: "Seja um voluntário",
          type: "info",
          parentId: null,
          order: 11,
          isActive: true,
          requiredRole: "user",
          icon: "volunteer",
          quickReply: false,
          content:
            "*Áreas de Serviço Disponíveis:*\n\n• Recepção e Acolhimento\n• Limpeza e Manutenção\n• Mídia e Tecnologia\n• Intercessão e Oração\n• Evangelismo e Missões\n• Ação Social\n\n*Treinamentos:*\nPrimeiro Sábado de cada mês, 14h00",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "volunteers", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.641Z"),
          updatedAt: new Date("2025-11-21T02:39:30.641Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8ef"),
          title: "🛍️ Loja",
          description: "Nossa loja de produtos",
          type: "info",
          parentId: null,
          order: 12,
          isActive: true,
          requiredRole: "user",
          icon: "store",
          quickReply: false,
          content:
            "*Produtos Disponíveis:*\n\n📚 *Livros e Bíblias*\n🎵 *Mídia e Música*\n👕 *Produtos Personalizados*\n\n*Encomendas:*\n📞 +258 84 600 7000\n✉️ store@cfcpush.org",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "store", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.641Z"),
          updatedAt: new Date("2025-11-21T02:39:30.641Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8f0"),
          title: "📍 Localização",
          description: "Onde nos encontrar",
          type: "info",
          parentId: null,
          order: 13,
          isActive: true,
          requiredRole: "user",
          icon: "location",
          quickReply: false,
          content:
            "*Endereço da Sede:*\n🏛️ CFC PUSH - Igreja da Família Cristã\nAv. 25 de Setembro, 1234\nMaputo, Moçambique\n\n*Contatos Gerais:*\n📞 +258 84 300 4000\n✉️ info@cfcpush.org\n🌐 www.cfcpush.org",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "location", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.641Z"),
          updatedAt: new Date("2025-11-21T02:39:30.641Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8f1"),
          title: "💰 PUSH Invest",
          description: "Investimentos e projetos",
          type: "submenu",
          parentId: null,
          order: 14,
          isActive: true,
          requiredRole: "user",
          icon: "investment",
          quickReply: false,
          content: "",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "investment", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.641Z"),
          updatedAt: new Date("2025-11-21T02:39:30.641Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8f2"),
          title: "❌ Encerrar",
          description: "Finalizar atendimento",
          type: "action",
          parentId: null,
          order: 15,
          isActive: true,
          requiredRole: "user",
          icon: "end",
          quickReply: false,
          content: "",
          url: "",
          payload: "END_CHAT",
          keywords: [],
          metadata: {
            module: "system",
            action: "end_chat",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.641Z"),
          updatedAt: new Date("2025-11-21T02:39:30.641Z"),
        },

        // SUBMENUS - Ser Membro (5 itens)
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8f4"),
          title: "📝 Novo Membro",
          description: "Faça seu cadastro",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8e4"),
          order: 1,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "🎯 *CADASTRO DE NOVO MEMBRO*\n\nSeja bem-vindo à família CFC PUSH! 🏛️✨\n\n*Preencha o formulário para:*\n✅ Tornar-se membro oficial\n✅ Receber boas-vindas pastoral\n✅ Participar de atividades exclusivas\n✅ Integrar-se na comunidade\n✅ Receber acompanhamento espiritual\n\n*Processo simples e rápido:*\n1. Preencha seus dados\n2. Aguarde contato da equipe\n3. Participe do culto de integração\n\n🔗 *Clique para cadastrar-se:*\nhttps://cfcpush.org/form/member-registration\n\n*Volte aqui após o cadastro!*",
          url: "https://cfcpush.org/form/member-registration",
          payload: "",
          keywords: [],
          metadata: {
            module: "members",
            action: "create",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.904Z"),
          updatedAt: new Date("2025-11-21T02:39:30.904Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8f5"),
          title: "🔄 Transferência",
          description: "Transferência de igreja",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8e4"),
          order: 2,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "🔄 *TRANSFERÊNCIA DE IGREJA*\n\nJá é membro de outra igreja e deseja transferir-se para a CFC PUSH? 🔄\n\n*Para quem é:*\n🏛️ Membros de outras denominações\n🚶‍♂️ Quem mudou de cidade\n💫 Buscando nova família espiritual\n\n*Documentos necessários:*\n📄 Carta de transferência\n📋 Dados pessoais atualizados\n📞 Contato da igreja anterior\n\n🔗 *Solicitar transferência:*\nhttps://cfcpush.org/form/member-transfer\n\n*Processo concluído em 7 dias úteis*",
          url: "https://cfcpush.org/form/member-transfer",
          payload: "",
          keywords: [],
          metadata: {
            module: "members",
            action: "transfer",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.904Z"),
          updatedAt: new Date("2025-11-21T02:39:30.904Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8f6"),
          title: "✏️ Atualizar Dados",
          description: "Atualize suas informações",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8e4"),
          order: 3,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "✏️ *ATUALIZAR DADOS CADASTRAIS*\n\nMudou de endereço, telefone ou situação familiar? Mantenha seus dados atualizados! 📝\n\n*O que pode atualizar:*\n🏠 Endereço residencial\n📞 Números de telefone\n💼 Profissão e situação laboral\n👨‍👩‍👧‍👦 Situação familiar\n📧 E-mail e contatos\n\n*Importante para:*\n✅ Receber visitas pastorais\n✅ Participar de eventos\n✅ Comunicados importantes\n✅ Benefícios da membresia\n\n🔗 *Atualizar dados:*\nhttps://cfcpush.org/form/update-data\n\n*Sua informação está segura conosco!* 🔒",
          url: "https://cfcpush.org/form/update-data",
          payload: "",
          keywords: [],
          metadata: {
            module: "members",
            action: "update",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.904Z"),
          updatedAt: new Date("2025-11-21T02:39:30.904Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8f7"),
          title: "📋 Direitos/Deveres",
          description: "Conheça direitos e deveres",
          type: "info",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8e4"),
          order: 4,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "⚖️ *DIREITOS E DEVERES DOS MEMBROS*\n\n*DIREITOS:*\n✅ Participar de cultos e atividades\n✅ Votar em assembleias gerais\n✅ Receber visita pastoral regular\n✅ Usufruir dos benefícios espirituais\n✅ Participar dos ministérios\n✅ Receber aconselhamento pastoral\n✅ Usar as instalações da igreja\n\n*DEVERES:*\n📅 Frequência aos cultos dominicais\n💝 Contribuição financeira regular\n🤝 Participação ativa na comunidade\n🙏 Testemunho cristão coerente\n📚 Respeito à doutrina e liderança\n🏠 Compromisso com a família da fé\n\n*CFC PUSH - Uma família em Cristo!* 🙏",
          url: "",
          payload: "",
          keywords: [],
          metadata: {
            module: "members",
            action: "rights",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.905Z"),
          updatedAt: new Date("2025-11-21T02:39:30.905Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8f8"),
          title: "🏠 Voltar ao Menu Principal",
          description: "Voltar ao menu anterior",
          type: "action",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8e4"),
          order: 5,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content: "",
          url: "",
          payload: "BACK_TO_MAIN",
          keywords: [],
          metadata: {
            module: "navigation",
            action: "back",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.905Z"),
          updatedAt: new Date("2025-11-21T02:39:30.905Z"),
        },

        // SUBMENUS - Oração (5 itens)
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8f9"),
          title: "❤️ Saúde",
          description: "Oração por saúde",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8e5"),
          order: 1,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            '❤️ *PEDIDO DE ORAÇÃO - SAÚDE*\n\nEstá passando por desafios de saúde? Nossa equipe de intercessão está pronta para orar por você! 🙏\n\n*Para que situações:*\n🏥 Tratamentos médicos e cirurgias\n💊 Doenças e enfermidades\n😔 Saúde mental e emocional\n👶 Gestação e parto\n👵 Idosos e cuidados paliativos\n\n*Como funciona:*\n1. Preencha o formulário\n2. Nossa equipe ora imediatamente\n3. Você recebe confirmação\n4. Acompanhamos seu caso\n\n🔗 *Enviar pedido de oração:*\nhttps://cfcpush.org/form/prayer-request?type=health\n\n*"A oração de um justo pode muito em seus efeitos." - Tiago 5:16*',
          url: "https://cfcpush.org/form/prayer-request?type=health",
          payload: "",
          keywords: [],
          metadata: { module: "prayer", action: "health", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.905Z"),
          updatedAt: new Date("2025-11-21T02:39:30.905Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8fa"),
          title: "👨‍👩‍👧‍👦 Família",
          description: "Oração pela família",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8e5"),
          order: 2,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "👨‍👩‍👧‍👦 *ORAÇÃO PELA FAMÍLIA*\n\nSua família precisa de oração? Estamos aqui para interceder por seus entes queridos! 🏠\n\n*Situações familiares:*\n💔 Conflitos e reconciliação\n👨‍👩‍👧‍👦 Relacionamentos familiares\n👶 Crianças e adolescentes\n🎓 Estudos e futuro profissional\n💼 Desafios financeiros\n🛡️ Proteção espiritual do lar\n\n*Benefícios:*\n✅ Oração específica por cada membro\n✅ Aconselhamento familiar disponível\n✅ Acompanhamento pastoral\n✅ Recursos para fortalecimento familiar\n\n🔗 *Solicitar oração familiar:*\nhttps://cfcpush.org/form/prayer-request?type=family\n\n*Deus abençoe seu lar!* ✨",
          url: "https://cfcpush.org/form/prayer-request?type=family",
          payload: "",
          keywords: [],
          metadata: { module: "prayer", action: "family", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.905Z"),
          updatedAt: new Date("2025-11-21T02:39:30.905Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8fb"),
          title: "💰 Finanças",
          description: "Oração por finanças",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8e5"),
          order: 3,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            '💰 *ORAÇÃO POR FINANÇAS E PROVISÃO*\n\nDesafios financeiros? Deus é nosso provedor! Ore conosco por breaktrough financeiro! 💫\n\n*Para que áreas:*\n💼 Emprego e oportunidades\n🏢 Negócios e empreendimentos\n📚 Estudos e capacitação\n🏠 Contas e obrigações\n🛒 Necessidades básicas\n📈 Investimentos e crescimento\n\n*O que oferecemos:*\n🙏 Oração específica por provisão\n💡 Orientação bíblica sobre finanças\n🤝 Apoio da comunidade\n📊 Recursos de educação financeira\n\n🔗 *Pedir oração financeira:*\nhttps://cfcpush.org/form/prayer-request?type=finance\n\n*"O meu Deus suprirá todas as necessidades de vocês" - Filipenses 4:19*',
          url: "https://cfcpush.org/form/prayer-request?type=finance",
          payload: "",
          keywords: [],
          metadata: {
            module: "prayer",
            action: "finance",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.905Z"),
          updatedAt: new Date("2025-11-21T02:39:30.905Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8fc"),
          title: "📝 Outros",
          description: "Outros pedidos de oração",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8e5"),
          order: 4,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "📝 *OUTROS PEDIDOS DE ORAÇÃO*\n\nTem alguma necessidade específica que não se enquadra nas categorias anteriores? Conte-nos! 🙏\n\n*Outras situações:*\n🎓 Decisões importantes\n🛣️ Viagens e deslocamentos\n⚖️ Questões legais\n🎯 Projetos e objetivos\n🤝 Relacionamentos\n🕊️ Paz interior e direção\n📖 Discernimento espiritual\n\n*Nosso compromisso:*\n✅ Oração personalizada\n✅ Sigilo absoluto\n✅ Acompanhamento espiritual\n✅ Suporte da comunidade\n\n🔗 *Enviar pedido personalizado:*\nhttps://cfcpush.org/form/prayer-request?type=other\n\n*Nada é pequeno demais para Deus!* 💝",
          url: "https://cfcpush.org/form/prayer-request?type=other",
          payload: "",
          keywords: [],
          metadata: { module: "prayer", action: "other", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.905Z"),
          updatedAt: new Date("2025-11-21T02:39:30.905Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8fd"),
          title: "🏠 Voltar ao Menu Principal",
          description: "Voltar ao menu anterior",
          type: "action",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8e5"),
          order: 5,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content: "",
          url: "",
          payload: "BACK_TO_MAIN",
          keywords: [],
          metadata: {
            module: "navigation",
            action: "back",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.905Z"),
          updatedAt: new Date("2025-11-21T02:39:30.905Z"),
        },

        // SUBMENUS - Assistência (5 itens)
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8fe"),
          title: "🛒 Alimentar",
          description: "Assistência alimentar",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8ea"),
          order: 1,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "🛒 *ASSISTÊNCIA ALIMENTAR*\n\nPassando por dificuldades para prover alimentação para sua família? Podemos ajudar! 🍞\n\n*O que oferecemos:*\n📦 Cestas básicas mensais\n🥦 Alimentos frescos quando disponíveis\n🍲 Refeições comunitárias\n👶 Alimentação infantil\n\n*Critérios:*\n🏠 Situação de vulnerabilidade comprovada\n👨‍👩‍👧‍👦 Número de dependentes\n📋 Avaliação da equipe social\n🔄 Acompanhamento mensal\n\n*Processo:*\n1. Preencha o formulário\n2. Avaliação em 48 horas\n3. Entrega agendada\n4. Acompanhamento contínuo\n\n🔗 *Solicitar assistência alimentar:*\nhttps://cfcpush.org/form/assistance?type=food\n\n*CFC PUSH - Servindo com Amor!* ❤️",
          url: "https://cfcpush.org/form/assistance?type=food",
          payload: "",
          keywords: [],
          metadata: {
            module: "assistance",
            action: "food",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.905Z"),
          updatedAt: new Date("2025-11-21T02:39:30.905Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd8ff"),
          title: "🏥 Médica",
          description: "Assistência médica",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8ea"),
          order: 2,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "🏥 *ASSISTÊNCIA MÉDICA E SAÚDE*\n\nPrecisa de apoio com questões de saúde? Nossa equipe está aqui para ajudar! 💊\n\n*Apoio disponível:*\n🩺 Consultas médicas básicas\n💊 Medicamentos essenciais\n🚑 Encaminhamentos hospitalares\n🧠 Apoio psicológico\n🦷 Cuidados odontológicos\n👵 Cuidados geriátricos\n\n*Como funciona:*\n📋 Avaliação da necessidade\n👨‍⚕️ Encaminhamento para profissionais\n💝 Apoio conforme disponibilidade\n🙏 Acompanhamento espiritual\n\n🔗 *Solicitar assistência médica:*\nhttps://cfcpush.org/form/assistance?type=medical\n\n*Tempo de resposta: 24-72 horas*",
          url: "https://cfcpush.org/form/assistance?type=medical",
          payload: "",
          keywords: [],
          metadata: {
            module: "assistance",
            action: "medical",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.905Z"),
          updatedAt: new Date("2025-11-21T02:39:30.905Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd900"),
          title: "⚖️ Jurídica",
          description: "Assistência jurídica",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8ea"),
          order: 3,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "⚖️ *ASSISTÊNCIA JURÍDICA*\n\nEnfrentando questões legais? Oferecemos orientação e apoio jurídico! 📚\n\n*Áreas de atuação:*\n📝 Documentação civil\n👨‍👩‍👧‍👦 Direito de família\n🏠 Questões habitacionais\n💼 Direito trabalhista\n📄 Regularização documental\n🛡️ Defesa dos direitos\n\n*Serviços:*\n💡 Orientação jurídica inicial\n📋 Encaminhamento para advogados\n📞 Mediação de conflitos\n🏛️ Acompanhamento em processos\n\n*Importante:*\n⚠️ Não substitui advogado particular\n📅 Agendamento necessário\n🔒 Confidencialidade garantida\n\n🔗 *Solicitar assistência jurídica:*\nhttps://cfcpush.org/form/assistance?type=legal\n\n*Justiça e misericórdia andam juntas!* ⚖️",
          url: "https://cfcpush.org/form/assistance?type=legal",
          payload: "",
          keywords: [],
          metadata: {
            module: "assistance",
            action: "legal",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.905Z"),
          updatedAt: new Date("2025-11-21T02:39:30.905Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd901"),
          title: "📝 Outra",
          description: "Outra assistência",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8ea"),
          order: 4,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "📝 *OUTRAS FORMAS DE ASSISTÊNCIA*\n\nTem uma necessidade específica que não se enquadra nas categorias anteriores? Conte-nos! 🤝\n\n*Outros tipos de apoio:*\n🎓 Material escolar e educacional\n👕 Vestuário e calçados\n🏠 Apoio habitacional emergencial\n🚗 Transporte para tratamentos\n💡 Capacitação profissional\n🎯 Inserção no mercado de trabalho\n\n*Processo:*\n1. Descrição detalhada da necessidade\n2. Avaliação pela equipe social\n3. Proposta de solução\n4. Acompanhamento personalizado\n\n🔗 *Solicitar outra assistência:*\nhttps://cfcpush.org/form/assistance?type=other\n\n*Cada necessidade é única e importante!* 💫",
          url: "https://cfcpush.org/form/assistance?type=other",
          payload: "",
          keywords: [],
          metadata: {
            module: "assistance",
            action: "other",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.905Z"),
          updatedAt: new Date("2025-11-21T02:39:30.905Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd902"),
          title: "🏠 Voltar ao Menu Principal",
          description: "Voltar ao menu anterior",
          type: "action",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8ea"),
          order: 5,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content: "",
          url: "",
          payload: "BACK_TO_MAIN",
          keywords: [],
          metadata: {
            module: "navigation",
            action: "back",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },

        // SUBMENUS - Núcleos (6 itens)
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd903"),
          title: "🗺️ Zona Norte",
          description: "Núcleo Zona Norte",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8eb"),
          order: 1,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "📍 *NÚCLEO ZONA NORTE*\n\nJunte-se à nossa comunidade na Zona Norte! 🌟\n\n*Responsável:* Irmão João\n📞 +258 84 123 4567\n\n*Local:* Centro Comunitário do Bairro\nAv. Norte, 567 - Maputo\n\n*Horários e Atividades:*\n📅 Quintas: 18h00 - Estudo Bíblico\n📅 Domingos: 16h00 - Celebração Comunitária\n📅 Sábados: 10h00 - Ação Social\n\n*O que oferecemos:*\n🙏 Cultos intimistas e acolhedores\n📖 Estudos bíblicos profundos\n🤝 Comunidade próxima e solidária\n👨‍👩‍👧‍👦 Atividades familiares\n💝 Apoio mútuo entre irmãos\n\n🔗 *Entrar no grupo do WhatsApp:*\nhttps://chat.whatsapp.com/CFCNorte123\n\n*Venha fazer parte da nossa família!* 🏠",
          url: "https://chat.whatsapp.com/CFCNorte123",
          payload: "",
          keywords: [],
          metadata: { module: "nucleus", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd904"),
          title: "🗺️ Zona Sul",
          description: "Núcleo Zona Sul",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8eb"),
          order: 2,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "📍 *NÚCLEO ZONA SUL*\n\nComunidade vibrante na Zona Sul te espera! ✨\n\n*Responsável:* Irmã Maria\n📞 +258 84 234 5678\n\n*Local:* Casa de Família\nRua Sul, 890 - Maputo\n\n*Horários e Atividades:*\n📅 Terças: 18h00 - Oração e Intercessão\n📅 Sábados: 17h00 - Comunhão e Lanche\n📅 Domingos: 15h00 - Escola Dominical\n\n*Destaques:*\n🔥 Grupos de intercessão ativos\n👶 Ministério infantil fortalecido\n🎵 Momentos de louvor especiais\n🤲 Ações sociais regulares\n\n🔗 *Entrar no grupo do WhatsApp:*\nhttps://chat.whatsapp.com/CFCSul123\n\n*Crescemos juntos na fé!* 🌱",
          url: "https://chat.whatsapp.com/CFCSul123",
          payload: "",
          keywords: [],
          metadata: { module: "nucleus", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd905"),
          title: "🗺️ Zona Leste",
          description: "Núcleo Zona Leste",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8eb"),
          order: 3,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "📍 *NÚCLEO ZONA LESTE*\n\nFamília cristã crescendo na Zona Leste! 💫\n\n*Responsável:* Irmão Pedro\n📞 +258 84 345 6789\n\n*Local:* Escola Primária\nAv. Leste, 123 - Maputo\n\n*Horários e Atividades:*\n📅 Quartas: 17h30 - Estudo Bíblico\n📅 Domingos: 15h00 - Culto Familiar\n📅 Sextas: 19h00 - Jovens\n\n*Características:*\n👨‍👩‍👧‍👦 Forte enfoque familiar\n🎯 Discipulado personalizado\n📚 Escola bíblica sólida\n🌟 Ambiente acolhedor\n\n🔗 *Entrar no grupo do WhatsApp:*\nhttps://chat.whatsapp.com/CFCLeste123\n\n*Sua nova família te espera!* ❤️",
          url: "https://chat.whatsapp.com/CFCLeste123",
          payload: "",
          keywords: [],
          metadata: { module: "nucleus", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd906"),
          title: "🗺️ Zona Oeste",
          description: "Núcleo Zona Oeste",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8eb"),
          order: 4,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "📍 *NÚCLEO ZONA OESTE*\n\nComunidade ativa e amorosa na Zona Oeste! 🙏\n\n*Responsável:* Irmã Ana\n📞 +258 84 456 7890\n\n*Local:* Salão Paroquial\nRua Oeste, 456 - Maputo\n\n*Horários e Atividades:*\n📅 Segundas: 18h00 - Intercessão\n📅 Sextas: 17h00 - CFC Jovens\n📅 Domingos: 16h30 - Celebração\n\n*Destaques:*\n🔥 Forte movimento de jovens\n🙏 Grupos de oração fervorosos\n🤝 Integração comunitária\n💝 Ações sociais transformadoras\n\n🔗 *Entrar no grupo do WhatsApp:*\nhttps://chat.whatsapp.com/CFCOeste123\n\n*Junte-se a nós!* 🎉",
          url: "https://chat.whatsapp.com/CFCOeste123",
          payload: "",
          keywords: [],
          metadata: { module: "nucleus", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd907"),
          title: "🗺️ Centro",
          description: "Núcleo Centro",
          type: "link",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8eb"),
          order: 5,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "📍 *NÚCLEO CENTRO*\n\nCoração da CFC PUSH no centro da cidade! 🏛️\n\n*Responsável:* Irmão Carlos\n📞 +258 84 567 8901\n\n*Local:* Sede CFC PUSH\nAv. 25 de Setembro, 1234 - Maputo\n\n*Horários e Atividades:*\n📅 Programação diária completa\n📅 Cultos principais aos domingos\n📅 Eventos especiais regulares\n📅 Todas as atividades da sede\n\n*Vantagens:*\n✅ Todas as programações principais\n✅ Estrutura completa disponível\n✅ Liderança pastoral direta\n✅ Todos os ministérios ativos\n✅ Eventos especiais frequentes\n\n🔗 *Entrar no grupo do WhatsApp:*\nhttps://chat.whatsapp.com/CFCCentro123\n\n*O centro de tudo acontece aqui!* ⭐",
          url: "https://chat.whatsapp.com/CFCCentro123",
          payload: "",
          keywords: [],
          metadata: { module: "nucleus", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd908"),
          title: "🏠 Voltar ao Menu Principal",
          description: "Voltar ao menu anterior",
          type: "action",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8eb"),
          order: 6,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content: "",
          url: "",
          payload: "BACK_TO_MAIN",
          keywords: [],
          metadata: {
            module: "navigation",
            action: "back",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },

        // SUBMENUS - Ministérios (6 itens)
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd909"),
          title: "🎵 Louvor e Adoração",
          description: "Ministério de Louvor",
          type: "info",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8ec"),
          order: 1,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            '🎵 *MINISTÉRIO DE LOUVOR E ADORAÇÃO*\n\nLevantamos vozes e instrumentos para glorificar a Deus! 🎶\n\n*Responsável:* Irmão João Silva\n📞 +258 84 123 4567\n✉️ louvor@cfcpush.org\n\n*Atividades:*\n📅 Quintas 19h00 - Ensaios gerais\n📅 Domingos - Liderança nos cultos\n📅 Eventos especiais - Apresentações\n📅 Sábados 15h00 - Treinamento de novos talentos\n\n*Requisitos para participação:*\n🎤 Habilidade vocal ou musical\n🙏 Compromisso com a fé cristã\n📅 Disponibilidade para ensaios\n🤝 Espírito de equipe\n🎯 Disposição para servir\n\n*Instrumentos necessários:*\n🎹 Teclado/Piano 🎸 Guitarra/Baixo\n🥁 Bateria/Percussão 🎤 Vocais\n\n*"Louvem ao SENHOR com harpa..." - Salmo 33:2*',
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "ministries", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd90a"),
          title: "🙏 Intercessão",
          description: "Ministério de Intercessão",
          type: "info",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8ec"),
          order: 2,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            '🙏 *MINISTÉRIO DE INTERCESSÃO*\n\nGuerreiros de oração que movem o céu pela terra! ⚔️\n\n*Responsável:* Irmã Maria Santos\n📞 +258 84 234 5678\n✉️ intercessao@cfcpush.org\n\n*Encontros:*\n📅 Segundas 18h00 - Reunião de intercessão\n📅 Último sábado do mês - Vigília de oração\n📅 Diariamente - Cadeia de oração 24h\n\n*Áreas de atuação:*\n🛡️ Oração pela liderança da igreja\n💒 Intercessão pelos membros\n🏙️ Oração pela cidade e nação\n🌍 Missões e evangelismo\n👥 Grupos específicos de oração\n\n*Características do intercessor:*\n📖 Vida de oração consistente\n💝 Coração sensível às necessidades\n🕰️ Disponibilidade para horários flexíveis\n🔊 Discernimento espiritual\n🤲 Fé para ver milagres\n\n*"A oração de um justo pode muito em seus efeitos." - Tiago 5:16*',
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "ministries", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd90b"),
          title: "🔥 CFC Youth",
          description: "Ministério Jovem",
          type: "info",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8ec"),
          order: 3,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "🔥 *CFC YOUTH - MINISTÉRIO JOVEM*\n\nJovens apaixonados por Jesus fazendo a diferença! 💥\n\n*Responsável:* Irmão Pedro Mondlane\n📞 +258 84 345 6789\n✉️ youth@cfcpush.org\n\n*Público-alvo:*\n🎯 Jovens de 15 a 30 anos\n🎓 Estudantes e profissionais\n🌟 Solteiros e jovens casais\n\n*Programação:*\n📅 Sextas 18h00 - Culto Jovem\n📅 Sábados 15h00 - Encontros e atividades\n📅 Domingos 17h00 - Pequenos grupos\n📅 Eventos mensais - Retiros e conferências\n\n*Atividades:*\n🎵 Louvor jovem e contemporâneo\n📚 Estudos bíblicos relevantes\n🎯 Desenvolvimento de liderança\n🤝 Networking e amizades saudáveis\n🎉 Eventos sociais e esportivos\n💡 Workshops e capacitação\n\n*Venha fazer parte da revolução jovem!* 🚀",
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "ministries", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd90c"),
          title: "👶 CFC Kids",
          description: "Ministério Infantil",
          type: "info",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8ec"),
          order: 4,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            '👶 *CFC KIDS - MINISTÉRIO INFANTIL*\n\nPlantando a semente do Evangelho nos corações das crianças! 🌱\n\n*Responsável:* Irmã Ana Pereira\n📞 +258 84 456 7890\n✉️ kids@cfcpush.org\n\n*Faixas etárias:*\n👶 3-5 anos - Maternal\n🧒 6-8 anos - Infantil I\n👦 9-12 anos - Infantil II\n\n*Horários:*\n📅 Domingos 9h-12h - Escola Bíblica Infantil\n📅 Sábados 10h00 - Programação especial\n📅 Feriados - Atividades temáticas\n\n*Metodologia:*\n🎨 Aprendizado através de brincadeiras\n📖 Histórias bíblicas criativas\n🎵 Músicas e coreografias infantis\n🎭 Teatro e dramatizações\n🧩 Atividades manuais e artísticas\n\n*Segurança:*\n✅ Equipe treinada e capacitada\n✅ Ambiente seguro e adequado\n✅ Protocolos de segurança implementados\n✅ Comunicação com os pais\n\n*"Deixem vir a mim as crianças..." - Marcos 10:14*',
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "ministries", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd90d"),
          title: "🤝 Social",
          description: "Ministério de Ação Social",
          type: "info",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8ec"),
          order: 5,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            '🤝 *MINISTÉRIO DE AÇÃO SOCIAL*\n\nMãos que servem, corações que amam! ❤️\n\n*Responsável:* Irmão Carlos Nhaca\n📞 +258 84 567 8901\n✉️ social@cfcpush.org\n\n*Reuniões:*\n📅 Terças 17h00 - Planejamento e organização\n📅 Sábados 8h-12h - Ações práticas\n\n*Projetos em andamento:*\n🛒 Distribuição de cestas básicas\n🏠 Visitas a asilos e orfanatos\n🎓 Apoio educacional a crianças carentes\n💊 Campanhas de saúde preventiva\n👵 Acompanhamento de idosos\n🏘️ Transformação comunitária\n\n*Voluntariado:*\n✅ Não requer qualificação específica\n💝 Apenas coração disposto a servir\n🕰️ Flexibilidade de horários\n🤲 Diversas áreas de atuação\n\n*Como participar:*\n1. Compareça a uma reunião\n2. Conheça os projetos\n3. Escolha sua área de interesse\n4. Comece a fazer a diferença!\n\n*"O amor seja não fingido..." - Romanos 12:9*',
          url: "",
          payload: "",
          keywords: [],
          metadata: { module: "ministries", requiresAuth: false },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd90e"),
          title: "🏠 Voltar ao Menu Principal",
          description: "Voltar ao menu anterior",
          type: "action",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8ec"),
          order: 6,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content: "",
          url: "",
          payload: "BACK_TO_MAIN",
          keywords: [],
          metadata: {
            module: "navigation",
            action: "back",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },

        // SUBMENUS - PUSH Invest (4 itens)
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd90f"),
          title: "📊 Projetos",
          description: "Projetos PUSH Invest",
          type: "info",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8f1"),
          order: 1,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            '📊 *PUSH INVEST - PROJETOS*\n\nInvestindo no Reino de Deus e no desenvolvimento da nossa comunidade! 💰\n\n*Em Breve!* 🚧\n\nEstamos preparando projetos incríveis de investimento e desenvolvimento que transformarão vidas e comunidades.\n\n*Áreas de atuação planejadas:*\n🏢 Empreendimentos comunitários\n🌱 Agricultura sustentável\n🎓 Educação e capacitação\n💼 Geração de emprego e renda\n🏘️ Desenvolvimento habitacional\n🛒 Comércio justo e solidário\n\n*Objetivos:*\n✅ Auto-sustentação da igreja\n✅ Geração de recursos para obras sociais\n✅ Criação de empregos para membros\n✅ Desenvolvimento comunitário\n✅ Multiplicação de recursos\n\n*Fique atento às novidades!*\nEm breve teremos oportunidades incríveis para você investir no Reino!\n\n*"Trazei todos os dízimos à casa do tesouro..." - Malaquias 3:10*',
          url: "",
          payload: "",
          keywords: [],
          metadata: {
            module: "investment",
            action: "projects",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd910"),
          title: "💵 Investir",
          description: "Como investir",
          type: "info",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8f1"),
          order: 2,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            '💵 *PUSH INVEST - COMO INVESTIR*\n\n*Informação em Desenvolvimento* 📈\n\nNossa equipe está trabalhando diligentemente nas melhores oportunidades de investimento para você.\n\n*O que estamos preparando:*\n📈 Modelos de investimento seguros\n💼 Oportunidades com retorno social e financeiro\n🛡️ Mecanismos de proteção ao investidor\n📊 Transparência total nos processos\n🤝 Parcerias estratégicas\n\n*Princípios que nos guiam:*\n⭐ Honestidade e integridade\n🛡️ Segurança acima de tudo\n💝 Retorno social e espiritual\n📚 Educação financeira bíblica\n🤲 Gestão responsável\n\n*Em breve teremos novidades!*\nAcompanhe nossos canais para não perder as oportunidades.\n\n*"O que o homem semear, isso também ceifará." - Gálatas 6:7*',
          url: "",
          payload: "",
          keywords: [],
          metadata: {
            module: "investment",
            action: "invest",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd911"),
          title: "📞 Contato",
          description: "Contato PUSH Invest",
          type: "info",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8f1"),
          order: 3,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content:
            "📞 *PUSH INVEST - CONTATO*\n\n*Equipe Especializada* 👨‍💼\n\nEstamos aqui para esclarecer suas dúvidas sobre investimentos e projetos futuros.\n\n*Contatos:*\n📞 *Telefone:* +258 84 500 6000\n✉️ *Email:* invest@cfcpush.org\n🏛️ *Escritório:* Sede CFC PUSH\nAv. 25 de Setembro, 1234 - Maputo\n\n*Horário de Atendimento:*\n📅 Segunda a Sexta: 9h-17h\n📅 Sábado: 9h-12h\n\n*Nossa Equipe:*\n👨‍💼 Gestores financeiros credenciados\n📊 Analistas de investimento\n💼 Consultores especializados\n🛡️ Assessoria jurídica\n\n*Agende uma reunião:*\nLigue ou envie email para marcar um horário com nossa equipe especializada.\n\n*Estamos ansiosos para servir você!* 🙏",
          url: "",
          payload: "",
          keywords: [],
          metadata: {
            module: "investment",
            action: "contact",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
        {
          _id: new Types.ObjectId("691fd0e2164c28df39bbd912"),
          title: "🏠 Voltar ao Menu Principal",
          description: "Voltar ao menu anterior",
          type: "action",
          parentId: new Types.ObjectId("691fd0e2164c28df39bbd8f1"),
          order: 4,
          isActive: true,
          requiredRole: "user",
          icon: "",
          quickReply: false,
          content: "",
          url: "",
          payload: "BACK_TO_MAIN",
          keywords: [],
          metadata: {
            module: "navigation",
            action: "back",
            requiresAuth: false,
          },
          createdAt: new Date("2025-11-21T02:39:30.906Z"),
          updatedAt: new Date("2025-11-21T02:39:30.906Z"),
        },
      ];

      // Inserir menus
      const createdMenus = await Menu.insertMany(menusData);

      // Dados da mensagem de boas-vindas
      const welcomeMessageData = {
        title: "🏛️ CFC PUSH - Igreja da Família Cristã",
        message:
          "Shalom! 👋 Agradecemos por entrar em contato connosco. Somos a Igreja da Família Cristã, comprometida em servir e edificar vidas.",
        instructions: "*Para continuar, selecione uma das opções abaixo:*",
        quickTip:
          "💡 *Navegação rápida:* Digite [#] para voltar ao menu principal",
        isActive: true,
        version: "1.0",
      };

      await WelcomeMessage.create(welcomeMessageData);

      console.log("✅ Seeders executados com sucesso!");
      console.log(`📊 ${createdMenus.length} menus criados`);
      console.log(`👋 1 mensagem de boas-vindas criada`);
    } catch (error) {
      console.error("❌ Erro ao executar seeders:", error);
      throw error;
    }
  }

  async clear(): Promise<void> {
    try {
      await Menu.deleteMany({});
      await WelcomeMessage.deleteMany({});
      console.log("🗑️ Dados limpos com sucesso!");
    } catch (error) {
      console.error("❌ Erro ao limpar dados:", error);
      throw error;
    }
  }
}
